[tools]
bun = "latest"
node = "25"
rclone = "latest"
tmux = "latest"
ffmpeg = "latest"
github-cli = "latest"
neovim = "latest"
ripgrep = "latest"
direnv = "latest"
1password-cli = "latest"
lazygit = "latest"
zellij = "latest"
fd = "latest"
zoxide = "latest"
fzf = "latest"
yazi = "latest"
uv = "latest"
gemini-cli = "latest"
claude = "latest"
opencode = "latest"
amp = "latest"
codex = "latest"
