[tools]
bun = "latest"
node = "25"
rclone = "latest"
github-cli = "latest"
neovim = "latest"
ripgrep = "latest"
direnv = "latest"
lazygit = "latest"
zellij = "latest"
fd = "latest"
zoxide = "latest"
fzf = "latest"
yazi = "latest"
uv = "latest"
claude = "latest"
codex = "latest"
"github:shantur/CodeNomad" = "latest"
"npm:@just-every/code" = "latest"
"github:ebg1223/better-context" = "0.5.9.1"
"github:roberte777/zesh" = "latest"
"github:anomalyco/opencode" = "latest"
