[tools]
bun = "latest"
node = "25"
rclone = "latest"
github-cli = "latest"
neovim = "latest"
ripgrep = "latest"
direnv = "latest"
lazygit = "latest"
zellij = "latest"
fd = "latest"
zoxide = "latest"
fzf = "latest"
yazi = "latest"
uv = "latest"
claude = "latest"
codex = "latest"
"github:sst/opencode" = "latest"
"github:shantur/CodeNomad" = "latest"
"github:just-every/code" = "latest"

[alias]
coder = "github:just-every/code"
