[tools]
bun = "latest"
node = "25"
rclone = "latest"
github-cli = "latest"
neovim = "latest"
ripgrep = "latest"
direnv = "latest"
lazygit = "latest"
zellij = "latest"
fd = "latest"
zoxide = "latest"
fzf = "latest"
yazi = "latest"
uv = "latest"
claude = "latest"
codex = "latest"
"github:shantur/CodeNomad" = "latest"
"npm:@just-every/code" = "latest"
"npm:btca" = "latest"
"github:anomalyco/opencode" = "latest"
amp = "latest"
"npm:clawdbot" = "latest"
gemini-cli = "latest"
rust = "latest"
"cargo:shpool" = { version = "latest", os = ["linux"] }
"github:lusingander/serie" = "latest"

[tools."http:zmx"]
version = "0.2.0"

[tools."http:zmx".platforms]
# {{version}} is NOT supported here, so we must hardcode it.
linux-x64 = { url = "https://zmx.sh/a/zmx-0.2.0-linux-x86_64.tar.gz" }
linux-arm64 = { url = "https://zmx.sh/a/zmx-0.2.0-linux-aarch64.tar.gz" }
macos-x64 = { url = "https://zmx.sh/a/zmx-0.2.0-macos-x86_64.tar.gz" }
macos-arm64 = { url = "https://zmx.sh/a/zmx-0.2.0-macos-aarch64.tar.gz" }
