[tools]
bun = "latest"
node = "25"
rclone = "latest"
tmux = "latest"
ffmpeg = "latest"
github-cli = "latest"
neovim = "latest"
ripgrep = "latest"
direnv = "latest"
1password-cli = "latest"
lazygit = "latest"
zellij = "latest"
fd = "latest"
zoxide = "latest"
fzf = "latest"
yazi = "latest"
uv = "latest"
claude = "latest"
codex = "0.63.0"
"github:sst/opencode" = "1.0.105"
"github:shantur/CodeNomad" = "latest"
"github:just-every/code" = "0.5.2"
